import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const geisMontserrat = localFont({
//   src: "/Montserrat-VariableFont_wght.ttf",
//   variable: "--font-geist-montserrat",
//   weight: "100 900",
// });
const geisMontserrat = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-geist-montserrat",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geisMontserrat.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
